# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b07b1e3ddb78c789f8506f6cd5831c6c834c781e0269042229d74415a7fef61aeb27837c36f6549e844366db9cf2ad5b56984068a959a970d10d19071260aff

test:
  secret_key_base: 1ecdf33dbbbe4e1eea44c0d74ba09846f9e12611bb5757a285ba148ab03e1ebf22bc238b8b8fb6e80de6adeea9bd6ba7038a9ba62329d82b03ba612c4f86a41c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
